lul
PES-Innovation-Lab/git-practice-workshop pull request #21
Opened 2020-07-04 05:56 UTC by LaRuim

dgko

2020-07-04 05:57 UTC, LaRuim commented
commitme

2020-07-04 06:06 UTC, vrajashkr requested changes

2020-07-04 06:06 UTC, DarkAEther commented on p.txt
> +fakop[lkoijku
`Lorem ipsum` sounds better here

2020-07-11 12:34 UTC, LaRuim commented on p.txt
> +fakop[lkoijku
okie

2020-09-08 03:05 UTC, closed without merging